packages:
  - client
  - client-3d
  - client-dream
  - server
  - types
  - loadtest
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
  - electron
  - electron-winstaller
  - esbuild
  - msgpackr-extract
  - swiper
